
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 42;
  public static final int LTE = 18;
  public static final int UMINUS = 16;
  public static final int ARRAY = 38;
  public static final int CLOSE_SQUARE = 9;
  public static final int FOR = 32;
  public static final int MINUS = 13;
  public static final int SEMICOLON = 2;
  public static final int AND = 24;
  public static final int LT = 22;
  public static final int TYPE = 41;
  public static final int NIL = 26;
  public static final int IN = 36;
  public static final int OR = 23;
  public static final int COMMA = 4;
  public static final int DIV = 15;
  public static final int OPEN_SQUARE = 8;
  public static final int OPEN_CURLY = 10;
  public static final int ATTRIBUTION = 25;
  public static final int PLUS = 12;
  public static final int IF = 27;
  public static final int ID = 45;
  public static final int DOT = 5;
  public static final int OF = 39;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEQ = 17;
  public static final int BREAK = 34;
  public static final int EQ = 20;
  public static final int GTE = 19;
  public static final int OPEN_PARENTHESIS = 6;
  public static final int TIMES = 14;
  public static final int COLON = 3;
  public static final int CLOSE_CURLY = 11;
  public static final int ELSE = 29;
  public static final int STRING_CONSTANT = 44;
  public static final int TO = 33;
  public static final int WHILE = 30;
  public static final int LET = 35;
  public static final int THEN = 28;
  public static final int END = 37;
  public static final int CLOSE_PARENTHESIS = 7;
  public static final int GT = 21;
  public static final int VAR = 40;
  public static final int INTEGER_CONSTANT = 43;
  public static final int DO = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "DOT",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "OPEN_SQUARE",
  "CLOSE_SQUARE",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "UMINUS",
  "NEQ",
  "LTE",
  "GTE",
  "EQ",
  "GT",
  "LT",
  "OR",
  "AND",
  "ATTRIBUTION",
  "NIL",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "TO",
  "BREAK",
  "LET",
  "IN",
  "END",
  "ARRAY",
  "OF",
  "VAR",
  "TYPE",
  "FUNCTION",
  "INTEGER_CONSTANT",
  "STRING_CONSTANT",
  "ID"
  };
}

