
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LCBR = 5;
  public static final int SLASH = 12;
  public static final int UMINUS = 42;
  public static final int LSBR = 7;
  public static final int SEMI = 24;
  public static final int ARRAY = 38;
  public static final int FOR = 31;
  public static final int MINUS = 10;
  public static final int STAR = 11;
  public static final int AND = 19;
  public static final int LT = 15;
  public static final int RPAR = 4;
  public static final int TYPE = 37;
  public static final int NIL = 2;
  public static final int IN = 35;
  public static final int OR = 20;
  public static final int COMMA = 23;
  public static final int GEQ = 18;
  public static final int NUM = 43;
  public static final int PLUS = 9;
  public static final int IF = 26;
  public static final int ID = 45;
  public static final int DOT = 25;
  public static final int OF = 39;
  public static final int EOF = 0;
  public static final int RCBR = 6;
  public static final int EQUAL = 13;
  public static final int error = 1;
  public static final int BREAK = 33;
  public static final int RSBR = 8;
  public static final int ATTR = 21;
  public static final int COLON = 22;
  public static final int ELSE = 28;
  public static final int FUNC = 41;
  public static final int TO = 32;
  public static final int WHILE = 29;
  public static final int NEQUAL = 14;
  public static final int LET = 34;
  public static final int THEN = 27;
  public static final int LEQ = 17;
  public static final int END = 36;
  public static final int STRING = 44;
  public static final int LPAR = 3;
  public static final int GT = 16;
  public static final int VAR = 40;
  public static final int DO = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NIL",
  "LPAR",
  "RPAR",
  "LCBR",
  "RCBR",
  "LSBR",
  "RSBR",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "EQUAL",
  "NEQUAL",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "AND",
  "OR",
  "ATTR",
  "COLON",
  "COMMA",
  "SEMI",
  "DOT",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "TO",
  "BREAK",
  "LET",
  "IN",
  "END",
  "TYPE",
  "ARRAY",
  "OF",
  "VAR",
  "FUNC",
  "UMINUS",
  "NUM",
  "STRING",
  "ID"
  };
}

